refac: Removed output:export from next config js
Error: export const dynamic = "force-static"/export const revalidate not configured on route "/api" with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export

Solution: The files in api are requesting dynamically while it assumed that the export is SSG meaning static, by removing the output export  we can have dynamic generation